services:
  db:
    image: postgres:17
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${EXPOSED_PORT_DB}:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - app-network
  app:
    build: .
    ports:
      - "${EXPOSED_PORT_APP}:3000"
    command: npm start
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - DB_HOST=host.docker.internal
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - EXPOSED_PORT_DB=${EXPOSED_PORT_DB}

networks:
  app-network:
    driver: bridge

volumes:
  db_data:
    driver: local

  
